### ISSUE TITLE
Remove iOS specific code

### ISSUE THREAD

**Issue by stefounet** [fasterize/lazyload#9]
Scroll events work as expected since iOS8 so we should rollback this commit https://github.com/fasterize/lazyload/commit/37333b224149158f7b4378a31e266a8d19ca0ae9
Ref: http://developer.telerik.com/featured/scroll-event-change-ios-8-big-deal/

**Comment by abarre** [comment]
One solution is to detect when ios is superior to IOS 8 by parsing the User Agent

**Comment by stefounet** [comment]
iOS <= 7 is only 4% market share and it's decreasing
